# Generated by Django 4.0.4 on 2022-05-31 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='approve_status',
            field=models.IntegerField(default=0),
        ),
    ]
