# Generated by Django 4.0.4 on 2022-05-31 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='otp_sent',
            new_name='approve_status',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='otp',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='verified',
        ),
    ]
