# Generated by Django 4.0.4 on 2022-05-31 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_otp_sent_voter_approve_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='approve_status',
        ),
    ]
