# Generated by Django 4.0.4 on 2022-05-31 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_remove_voter_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='approve_status',
            field=models.IntegerField(default=0),
        ),
    ]
