# Generated by Django 4.0.4 on 2022-06-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_voter_approve_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='otp',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='otp_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
